# Generated by Django 2.1.7 on 2019-04-09 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 9, 20, 42, 7, 640658)),
        ),
    ]
