# Generated by Django 2.1.7 on 2019-04-09 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190409_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 9, 20, 43, 18, 370609)),
        ),
    ]
