# Generated by Django 2.1.7 on 2019-04-09 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190409_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 9, 21, 32, 35, 190754)),
        ),
        migrations.AlterField(
            model_name='image',
            name='side',
            field=models.CharField(default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='image',
            name='stage',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
